-- Insert routes
INSERT INTO BUS_ROUTE Values ("Federal Way TC", "Tukwila International Blvd Link Station", "671", 127);
INSERT INTO BUS_ROUTE Values ("Tukwila International Blvd Link Station", "Federal Way TC", "671", 127);
INSERT INTO BUS_ROUTE Values ("Bellevue TC", "Redmond TC", "672", 127);
INSERT INTO BUS_ROUTE Values ("Redmond TC", "Bellevue TC", "672", 127);
INSERT INTO BUS_ROUTE Values ("Westwood Village", "South Lake Union", "673", 127);
INSERT INTO BUS_ROUTE Values ("South Lake Union", "Westwood Village", "673", 127);
INSERT INTO BUS_ROUTE Values ("Crown Hill", "Downtown Seattle", "674", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Crown Hill", "674", 127);
INSERT INTO BUS_ROUTE Values ("Aurora Village", "Downtown Seattle", "675", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Aurora Village", "675", 127);
INSERT INTO BUS_ROUTE Values ("Burien", "The Landing", "676", 127);
INSERT INTO BUS_ROUTE Values ("The Landing", "Burien", "676", 127);
INSERT INTO BUS_ROUTE Values ("Kinnear", "Downtown Seattle", "1", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Kinnear", "1", 127);
INSERT INTO BUS_ROUTE Values ("Seattle Pacific", "Madrona Park", "2", 127);
INSERT INTO BUS_ROUTE Values ("Madrona Park", "Seattle Pacific", "2", 127);
INSERT INTO BUS_ROUTE Values ("Seattle Pacific University", "Madrona, Judkins Park", "3", 127);
INSERT INTO BUS_ROUTE Values ("Madrona, Judkins Park", "Seattle Pacific University", "3", 127);
INSERT INTO BUS_ROUTE Values ("Shoreline CC", "Downtown Seattle", "5", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Shoreline CC", "5", 127);
INSERT INTO BUS_ROUTE Values ("Prentice Street/Rainier Beach", "Downtown Seattle", "7", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Prentice Street/Rainier Beach", "7", 127);
INSERT INTO BUS_ROUTE Values ("Seattle Center", "Mt Baker TC", "8", 127);
INSERT INTO BUS_ROUTE Values ("Mt Baker TC", "Seattle Center", "8", 127);
INSERT INTO BUS_ROUTE Values ("Rainier Beach", "Broadway", "9", 124);
INSERT INTO BUS_ROUTE Values ("Broadway", "Rainier Beach", "9", 124);
INSERT INTO BUS_ROUTE Values ("Capitol Hill", "Downtown Seattle", "10", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Capitol Hill", "10", 127);
INSERT INTO BUS_ROUTE Values ("Madison Park", "Downtown Seattle", "11", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Madison Park", "11", 127);
INSERT INTO BUS_ROUTE Values ("Interlaken Park", "Downtown Seattle", "12", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Interlaken Park", "12", 127);
INSERT INTO BUS_ROUTE Values ("Seattle Pacific", "Madrona Park", "13", 127);
INSERT INTO BUS_ROUTE Values ("Madrona Park", "Seattle Pacific", "13", 127);
INSERT INTO BUS_ROUTE Values ("Mount Baker", "Downtown Seattle", "14", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Mount Baker", "14", 127);
INSERT INTO BUS_ROUTE Values ("Blue Ridge", "Downtown Seattle", "15", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Blue Ridge", "15", 124);
INSERT INTO BUS_ROUTE Values ("Sunset Hill", "Downtown Seattle", "17", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Sunset Hill", "17", 124);
INSERT INTO BUS_ROUTE Values ("North Beach", "Downtown Seattle", "18", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "North Beach", "18", 124);
INSERT INTO BUS_ROUTE Values ("West Magnolia", "Downtown Seattle", "19", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "West Magnolia", "19", 124);
INSERT INTO BUS_ROUTE Values ("Westwood Village", "Downtown Seattle", "21", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Westwood Village", "21", 127);
INSERT INTO BUS_ROUTE Values ("Arbor Heights", "Alaska Junction", "22", 127);
INSERT INTO BUS_ROUTE Values ("Alaska Junction", "Arbor Heights", "22", 127);
INSERT INTO BUS_ROUTE Values ("West Magnolia", "Downtown Seattle", "24", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "West Magnolia", "24", 127);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "Downtown Seattle", "26", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Northgate TC", "26", 127);
INSERT INTO BUS_ROUTE Values ("Colman Park", "Downtown Seattle", "27", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Colman Park", "27", 127);
INSERT INTO BUS_ROUTE Values ("Carkeek Park/Broadview", "Downtown Seattle", "28", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Carkeek Park/Broadview", "28", 127);
INSERT INTO BUS_ROUTE Values ("Ballard", "Downtown Seattle", "29", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Ballard", "29", 124);
INSERT INTO BUS_ROUTE Values ("Seattle Center Magnolia", "University District", "31", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Seattle Center Magnolia", "31", 127);
INSERT INTO BUS_ROUTE Values ("Discovery Park", "Downtown Seattle", "33", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Discovery Park", "33", 127);
INSERT INTO BUS_ROUTE Values ("Othello Station", "Downtown Seattle", "36", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Othello Station", "36", 127);
INSERT INTO BUS_ROUTE Values ("Alaska Junction", "Downtown Seattle", "37", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Alaska Junction", "37", 124);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "Downtown Seattle", "40", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Northgate TC", "40", 127);
INSERT INTO BUS_ROUTE Values ("Lake City", "Downtown Seattle", "41", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Lake City", "41", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Capitol Hill Downtown Seattle", "43", 127);
INSERT INTO BUS_ROUTE Values ("Capitol Hill Downtown Seattle", "University District", "43", 127);
INSERT INTO BUS_ROUTE Values ("Ballard", "UW Station", "44", 127);
INSERT INTO BUS_ROUTE Values ("UW Station", "Ballard", "44", 127);
INSERT INTO BUS_ROUTE Values ("Loyal Heights", "University District", "45", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Loyal Heights", "45", 127);
INSERT INTO BUS_ROUTE Values ("Summit", "Downtown Seattle", "47", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Summit", "47", 127);
INSERT INTO BUS_ROUTE Values ("Mt Baker TC", "University District", "48", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Mt Baker TC", "48", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Downtown Seattle", "49", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "University District", "49", 127);
INSERT INTO BUS_ROUTE Values ("Othello Station", "Alki", "50", 127);
INSERT INTO BUS_ROUTE Values ("Alki", "Othello Station", "50", 127);
INSERT INTO BUS_ROUTE Values ("Admiral District", "Downtown Seattle", "55", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Admiral District", "55", 124);
INSERT INTO BUS_ROUTE Values ("Alki/Alaska Junction", "Downtown Seattle", "56", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Alki/Alaska Junction", "56", 124);
INSERT INTO BUS_ROUTE Values ("Westwood Village", "Broadway", "60", 127);
INSERT INTO BUS_ROUTE Values ("Broadway", "Westwood Village", "60", 127);
INSERT INTO BUS_ROUTE Values ("Sand Point", "Downtown Seattle", "62", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Sand Point", "62", 127);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "Cherry Hill", "63", 124);
INSERT INTO BUS_ROUTE Values ("Cherry Hill", "Northgate TC", "63", 124);
INSERT INTO BUS_ROUTE Values ("Jackson Park", "Cherry Hill", "64", 124);
INSERT INTO BUS_ROUTE Values ("Cherry Hill", "Jackson Park", "64", 124);
INSERT INTO BUS_ROUTE Values ("Jackson Park", "University District", "65", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Jackson Park", "65", 127);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "Children’s Hospital", "67", 127);
INSERT INTO BUS_ROUTE Values ("Children’s Hospital", "Northgate TC", "67", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Downtown Seattle", "70", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "University District", "70", 127);
INSERT INTO BUS_ROUTE Values ("Wedgwood", "UW Station", "71", 127);
INSERT INTO BUS_ROUTE Values ("UW Station", "Wedgwood", "71", 127);
INSERT INTO BUS_ROUTE Values ("Jackson Park", "UW Station", "73", 127);
INSERT INTO BUS_ROUTE Values ("UW Station", "Jackson Park", "73", 127);
INSERT INTO BUS_ROUTE Values ("Sand Point", "Downtown Seattle", "74", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Sand Point", "74", 124);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "University District", "75", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Northgate TC", "75", 127);
INSERT INTO BUS_ROUTE Values ("Wedgwood", "Downtown Seattle", "76", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Wedgwood", "76", 124);
INSERT INTO BUS_ROUTE Values ("North City", "Downtown Seattle", "77", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "North City", "77", 124);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Downtown Seattle", "101", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Renton TC", "101", 127);
INSERT INTO BUS_ROUTE Values ("Fairwood", "Downtown Seattle", "102", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Fairwood", "102", 124);
INSERT INTO BUS_ROUTE Values ("Renton Highlands", "Renton TC", "105", 127);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Renton Highlands", "105", 127);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Downtown Seattle", "106", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Renton TC", "106", 127);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Beacon Hill", "107", 127);
INSERT INTO BUS_ROUTE Values ("Beacon Hill", "Renton TC", "107", 127);
INSERT INTO BUS_ROUTE Values ("Maplewood", "Downtown Seattle", "111", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Maplewood", "111", 124);
INSERT INTO BUS_ROUTE Values ("Shorewood", "Downtown Seattle", "113", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Shorewood", "113", 124);
INSERT INTO BUS_ROUTE Values ("Renton Highlands", "Downtown Seattle", "114", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Renton Highlands", "114", 124);
INSERT INTO BUS_ROUTE Values ("Fauntleroy Ferry", "Downtown Seattle", "116", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Fauntleroy Ferry", "116", 124);
INSERT INTO BUS_ROUTE Values ("Tahlequah Ferry", "Vashon Ferry", "118", 127);
INSERT INTO BUS_ROUTE Values ("Vashon Ferry", "Tahlequah Ferry", "118", 127);
INSERT INTO BUS_ROUTE Values ("Tahlequah", "Downtown Seattle", "118", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Tahlequah", "118", 124);
INSERT INTO BUS_ROUTE Values ("Burien TC", "Downtown Seattle", "120", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Burien TC", "120", 127);
INSERT INTO BUS_ROUTE Values ("Highline College", "Downtown Seattle", "121", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Highline College", "121", 124);
INSERT INTO BUS_ROUTE Values ("Highline College", "Downtown Seattle", "122", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Highline College", "122", 124);
INSERT INTO BUS_ROUTE Values ("Burien", "Downtown Seattle", "123", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Burien", "123", 124);
INSERT INTO BUS_ROUTE Values ("Tukwila International Blvd Link Station", "Downtown Seattle", "124", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Tukwila International Blvd Link Station", "124", 127);
INSERT INTO BUS_ROUTE Values ("Westwood Village", "Downtown Seattle", "125", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Westwood Village", "125", 127);
INSERT INTO BUS_ROUTE Values ("Admiral District", "Southcenter", "128", 127);
INSERT INTO BUS_ROUTE Values ("Southcenter", "Admiral District", "128", 127);
INSERT INTO BUS_ROUTE Values ("Burien TC", "Downtown Seattle", "131", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Burien TC", "131", 127);
INSERT INTO BUS_ROUTE Values ("Burien TC", "Downtown Seattle", "132", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Burien TC", "132", 127);
INSERT INTO BUS_ROUTE Values ("Black Diamond", "Downtown Seattle", "143", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Black Diamond", "143", 124);
INSERT INTO BUS_ROUTE Values ("Fairwood", "Renton TC", "148", 127);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Fairwood", "148", 127);
INSERT INTO BUS_ROUTE Values ("Kent Station", "Downtown Seattle", "150", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Kent Station", "150", 127);
INSERT INTO BUS_ROUTE Values ("Kent Station", "Renton TC", "153", 124);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Kent Station", "153", 124);
INSERT INTO BUS_ROUTE Values ("Auburn Station", "Federal Center South", "154", 124);
INSERT INTO BUS_ROUTE Values ("Federal Center South", "Auburn Station", "154", 124);
INSERT INTO BUS_ROUTE Values ("Highline College", "Southcenter", "156", 127);
INSERT INTO BUS_ROUTE Values ("Southcenter", "Highline College", "156", 127);
INSERT INTO BUS_ROUTE Values ("Lake Meridian P&R", "Downtown Seattle", "157", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Lake Meridian P&R", "157", 124);
INSERT INTO BUS_ROUTE Values ("Lake Meridian", "Downtown Seattle", "158", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Lake Meridian", "158", 124);
INSERT INTO BUS_ROUTE Values ("Covington", "Downtown Seattle", "159", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Covington", "159", 124);
INSERT INTO BUS_ROUTE Values ("Green River College", "Kent Station", "164", 127);
INSERT INTO BUS_ROUTE Values ("Kent Station", "Green River College", "164", 127);
INSERT INTO BUS_ROUTE Values ("Kent Station", "Burien TC", "166", 127);
INSERT INTO BUS_ROUTE Values ("Burien TC", "Kent Station", "166", 127);
INSERT INTO BUS_ROUTE Values ("South Renton P&R", "University District", "167", 124);
INSERT INTO BUS_ROUTE Values ("University District", "South Renton P&R", "167", 124);
INSERT INTO BUS_ROUTE Values ("Maple Valley", "Kent Station", "168", 127);
INSERT INTO BUS_ROUTE Values ("Kent Station", "Maple Valley", "168", 127);
INSERT INTO BUS_ROUTE Values ("Kent Station", "Renton TC", "169", 127);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Kent Station", "169", 127);
INSERT INTO BUS_ROUTE Values ("South Federal Way P&R", "Downtown Seattle", "177", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "South Federal Way P&R", "177", 124);
INSERT INTO BUS_ROUTE Values ("Twin Lakes P&R", "Downtown Seattle", "179", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Twin Lakes P&R", "179", 124);
INSERT INTO BUS_ROUTE Values ("Southeast Auburn", "Burien TC", "180", 127);
INSERT INTO BUS_ROUTE Values ("Burien TC", "Southeast Auburn", "180", 127);
INSERT INTO BUS_ROUTE Values ("Twin Lakes P&R", "Green River College", "181", 127);
INSERT INTO BUS_ROUTE Values ("Green River College", "Twin Lakes P&R", "181", 127);
INSERT INTO BUS_ROUTE Values ("Northeast Tacoma", "Federal Way TC", "182", 127);
INSERT INTO BUS_ROUTE Values ("Federal Way TC", "Northeast Tacoma", "182", 127);
INSERT INTO BUS_ROUTE Values ("Federal Way TC", "Kent Station", "183", 127);
INSERT INTO BUS_ROUTE Values ("Kent Station", "Federal Way TC", "183", 127);
INSERT INTO BUS_ROUTE Values ("Enumclaw", "Auburn Station", "186", 124);
INSERT INTO BUS_ROUTE Values ("Auburn Station", "Enumclaw", "186", 124);
INSERT INTO BUS_ROUTE Values ("Federal Way TC", "Twin Lakes, Federal Way TC", "187", 127);
INSERT INTO BUS_ROUTE Values ("Redondo Heights P&R", "Downtown Seattle", "190", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Redondo Heights P&R", "190", 124);
INSERT INTO BUS_ROUTE Values ("Star Lake", "Downtown Seattle", "192", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Star Lake", "192", 124);
INSERT INTO BUS_ROUTE Values ("Federal Way P&R", "First Hill", "193", 124);
INSERT INTO BUS_ROUTE Values ("First Hill", "Federal Way P&R", "193", 124);
INSERT INTO BUS_ROUTE Values ("Twin Lakes P&R", "University District", "197", 124);
INSERT INTO BUS_ROUTE Values ("University District", "Twin Lakes P&R", "197", 124);
INSERT INTO BUS_ROUTE Values ("Issaquah Community Center", "Swedish Medical Center", "200", 124);
INSERT INTO BUS_ROUTE Values ("Swedish Medical Center", "Issaquah Community Center", "200", 124);
INSERT INTO BUS_ROUTE Values ("South Mercer Island", "Mercer Island P&R (and University Street Tunnel Station)", "201", 124);
INSERT INTO BUS_ROUTE Values ("Mercer Island P&R (and University Street Tunnel Station)", "South Mercer Island", "201", 124);
INSERT INTO BUS_ROUTE Values ("South Mercer Island", "Mercer Island P&R (and Conventional Place Tunnel Station)", "204", 124);
INSERT INTO BUS_ROUTE Values ("Mercer Island P&R (and Conventional Place Tunnel Station)", "South Mercer Island", "204", 124);
INSERT INTO BUS_ROUTE Values ("North Bend", "Issaquah TC (Downtown Seattle)", "208", 127);
INSERT INTO BUS_ROUTE Values ("Issaquah TC (Downtown Seattle)", "North Bend", "208", 127);
INSERT INTO BUS_ROUTE Values ("Eastgate P&R", "Downtown Seattle", "212", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Eastgate P&R", "212", 124);
INSERT INTO BUS_ROUTE Values ("Issaquah TC", "Downtown Seattle", "214", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Issaquah TC", "214", 124);
INSERT INTO BUS_ROUTE Values ("Bear Creek P&R", "Downtown Seattle", "216", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Bear Creek P&R", "216", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "North Issaquah", "217", 124);
INSERT INTO BUS_ROUTE Values ("North Issaquah", "Downtown Seattle", "217", 124);
INSERT INTO BUS_ROUTE Values ("Redmond TC", "Eastgate P&R", "221", 127);
INSERT INTO BUS_ROUTE Values ("Eastgate P&R", "Redmond TC", "221", 127);
INSERT INTO BUS_ROUTE Values ("Duvall", "Redmond TC", "224", 124);
INSERT INTO BUS_ROUTE Values ("Redmond TC", "Duvall", "224", 124);
INSERT INTO BUS_ROUTE Values ("Eastgate P&R", "Bellevue TC", "226", 127);
INSERT INTO BUS_ROUTE Values ("Bellevue TC", "Eastgate P&R", "226", 127);
INSERT INTO BUS_ROUTE Values ("Duvall", "Bellevue TC", "232", 124);
INSERT INTO BUS_ROUTE Values ("Bellevue TC", "Duvall", "232", 124);
INSERT INTO BUS_ROUTE Values ("Kenmore P&R/Kingsgate P&R", "Bellevue TC", "234", 127);
INSERT INTO BUS_ROUTE Values ("Bellevue TC", "Kenmore P&R/Kingsgate P&R", "234", 127);
INSERT INTO BUS_ROUTE Values ("Woodinville P&R", "Kirkland TC", "236", 127);
INSERT INTO BUS_ROUTE Values ("Kirkland TC", "Woodinville P&R", "236", 127);
INSERT INTO BUS_ROUTE Values ("Woodinville P&R", "Bellevue TC", "237", 124);
INSERT INTO BUS_ROUTE Values ("Bellevue TC", "Woodinville P&R", "237", 124);
INSERT INTO BUS_ROUTE Values ("UW/CCC Campus, Woodinville P&R", "Kirkland TC", "238", 127);
INSERT INTO BUS_ROUTE Values ("Kirkland TC", "UW/CCC Campus, Woodinville P&R", "238", 127);
INSERT INTO BUS_ROUTE Values ("Bellevue TC", "Renton TC", "240", 127);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Bellevue TC", "240", 127);
INSERT INTO BUS_ROUTE Values ("Eastgate P&R", "Bellevue TC", "241", 127);
INSERT INTO BUS_ROUTE Values ("Bellevue TC", "Eastgate P&R", "241", 127);
INSERT INTO BUS_ROUTE Values ("Overlake TC", "Kenmore P&R", "243", 124);
INSERT INTO BUS_ROUTE Values ("Kenmore P&R", "Overlake TC", "243", 124);
INSERT INTO BUS_ROUTE Values ("Kenmore P&R", "Overlake TC", "244", 124);
INSERT INTO BUS_ROUTE Values ("Overlake TC", "Kenmore P&R", "244", 124);
INSERT INTO BUS_ROUTE Values ("Kirkland TC", "Factoria", "245", 127);
INSERT INTO BUS_ROUTE Values ("Factoria", "Kirkland TC", "245", 127);
INSERT INTO BUS_ROUTE Values ("Eastgate P&R", "Clyde Hill", "246", 124);
INSERT INTO BUS_ROUTE Values ("Clyde Hill", "Eastgate P&R", "246", 124);
INSERT INTO BUS_ROUTE Values ("Avondale", "Kirkland TC", "248", 127);
INSERT INTO BUS_ROUTE Values ("Kirkland TC", "Avondale", "248", 127);
INSERT INTO BUS_ROUTE Values ("Overlake TC", "South Bellevue", "249", 127);
INSERT INTO BUS_ROUTE Values ("South Bellevue", "Overlake TC", "249", 127);
INSERT INTO BUS_ROUTE Values ("Kingsgate/Brickyard P&R", "Downtown Seattle", "252", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Kingsgate/Brickyard P&R", "252", 124);
INSERT INTO BUS_ROUTE Values ("Brickyard P&R", "Downtown Seattle", "255", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Brickyard P&R", "255", 127);
INSERT INTO BUS_ROUTE Values ("Redmond", "Downtown Seattle", "268", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Redmond", "268", 124);
INSERT INTO BUS_ROUTE Values ("Issaquah TC", "Overlake P&R", "269", 124);
INSERT INTO BUS_ROUTE Values ("Overlake P&R", "Issaquah TC", "269", 124);
INSERT INTO BUS_ROUTE Values ("Issaquah", "University District", "271", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Issaquah", "271", 127);
INSERT INTO BUS_ROUTE Values ("Juanita", "University District", "277", 124);
INSERT INTO BUS_ROUTE Values ("University District", "Juanita", "277", 124);
INSERT INTO BUS_ROUTE Values ("Aurora Village TC", "Downtown Seattle", "301", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Aurora Village TC", "301", 124);
INSERT INTO BUS_ROUTE Values ("Shoreline P&R", "First Hill", "303", 124);
INSERT INTO BUS_ROUTE Values ("First Hill", "Shoreline P&R", "303", 124);
INSERT INTO BUS_ROUTE Values ("Richmond Beach", "Downtown Seattle", "304", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Richmond Beach", "304", 124);
INSERT INTO BUS_ROUTE Values ("Horizon View", "Downtown Seattle", "308", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Horizon View", "308", 124);
INSERT INTO BUS_ROUTE Values ("Kenmore P&R", "First Hill", "309", 124);
INSERT INTO BUS_ROUTE Values ("First Hill", "Kenmore P&R", "309", 124);
INSERT INTO BUS_ROUTE Values ("Woodinville", "Downtown Seattle", "311", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Woodinville", "311", 124);
INSERT INTO BUS_ROUTE Values ("UW/Cascadia Campus", "Downtown Seattle", "312", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "UW/Cascadia Campus", "312", 124);
INSERT INTO BUS_ROUTE Values ("Meridian Park", "Downtown Seattle", "316", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Meridian Park", "316", 124);
INSERT INTO BUS_ROUTE Values ("Shoreline Community College", "Lake City", "330", 124);
INSERT INTO BUS_ROUTE Values ("Lake City", "Shoreline Community College", "330", 124);
INSERT INTO BUS_ROUTE Values ("Shoreline", "Kenmore P&R (Bothell Campus)", "331", 127);
INSERT INTO BUS_ROUTE Values ("Kenmore P&R (Bothell Campus)", "Shoreline", "331", 127);
INSERT INTO BUS_ROUTE Values ("Shoreline P&R", "Renton TC", "342", 124);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Shoreline P&R", "342", 124);
INSERT INTO BUS_ROUTE Values ("Shoreline Community College", "Northgate TC", "345", 127);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "Shoreline Community College", "345", 127);
INSERT INTO BUS_ROUTE Values ("Aurora Village TC", "Northgate TC", "346", 127);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "Aurora Village TC", "346", 127);
INSERT INTO BUS_ROUTE Values ("Richmond Beach", "Northgate TC", "347", 127);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "Richmond Beach", "347", 127);
INSERT INTO BUS_ROUTE Values ("Shoreline Community College", "Downtown Seattle", "355", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Shoreline Community College", "355", 124);
INSERT INTO BUS_ROUTE Values ("Lake City/Bothell", "University District", "372", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Lake City/Bothell", "372", 127);
INSERT INTO BUS_ROUTE Values ("Aurora Village TC", "University District", "373", 124);
INSERT INTO BUS_ROUTE Values ("University District", "Aurora Village TC", "373", 124);
INSERT INTO BUS_ROUTE Values ("North Bend", "Issaquah Highlands P&R", "628", 124);
INSERT INTO BUS_ROUTE Values ("Issaquah Highlands P&R", "North Bend", "628", 124);
INSERT INTO BUS_ROUTE Values ("Mercer Island", "Downtown Seattle", "630", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Mercer Island", "630", 124);
INSERT INTO BUS_ROUTE Values ("Burien TC", "Highline Medical Center, Gregory Heights", "631", 124);
INSERT INTO BUS_ROUTE Values ("Angle Lake Station", "the Des Moines Marina District", "635", 124);
INSERT INTO BUS_ROUTE Values ("the Des Moines Marina District", "Angle Lake Station", "635", 124);
INSERT INTO BUS_ROUTE Values ("Alaska Junction, Seacrest Park", "Alaska Junction, Seacrest Park", "773", 127);
INSERT INTO BUS_ROUTE Values ("Admiral Junction, Alki, Seacrest Park", "Admiral Junction, Alki, Seacrest Park", "775", 127);
INSERT INTO BUS_ROUTE Values ("Mirror Lake", "Mirror Lake, Federal Way TC", "901", 127);
INSERT INTO BUS_ROUTE Values ("Twin Lakes", "Twin Lakes, Federal Way TC", "903", 127);
INSERT INTO BUS_ROUTE Values ("Fairwood", "Southcenter", "906", 127);
INSERT INTO BUS_ROUTE Values ("Southcenter", "Fairwood", "906", 127);
INSERT INTO BUS_ROUTE Values ("Black Diamond", "Renton TC", "907", 124);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Black Diamond", "907", 124);
INSERT INTO BUS_ROUTE Values ("Renton Highlands", "Renton TC", "908", 127);
INSERT INTO BUS_ROUTE Values ("Renton TC", "Renton Highlands", "908", 127);
INSERT INTO BUS_ROUTE Values ("The Outlet Collection Seattle", "North Auburn", "910", 127);
INSERT INTO BUS_ROUTE Values ("North Auburn", "The Outlet Collection Seattle", "910", 127);
INSERT INTO BUS_ROUTE Values ("Clockwise Loop", "Counter-clockwise Loop", "913", 124);
INSERT INTO BUS_ROUTE Values ("Counter-clockwise Loop", "Clockwise Loop", "913", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Kent", "Kent East Hill", "914", 127);
INSERT INTO BUS_ROUTE Values ("Kent East Hill", "Downtown Kent", "914", 127);
INSERT INTO BUS_ROUTE Values ("Enumclaw", "Auburn Station", "915", 127);
INSERT INTO BUS_ROUTE Values ("Auburn Station", "Enumclaw", "915", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Kent", "Kent East Hill", "916", 127);
INSERT INTO BUS_ROUTE Values ("Kent East Hill", "Downtown Kent", "916", 127);
INSERT INTO BUS_ROUTE Values ("White River Junction", "Auburn Station", "917", 127);
INSERT INTO BUS_ROUTE Values ("Auburn Station", "White River Junction", "917", 127);
INSERT INTO BUS_ROUTE Values ("Kingsgate P&R", "Redmond Town Center", "930", 124);
INSERT INTO BUS_ROUTE Values ("Redmond Town Center", "Kingsgate P&R", "930", 124);
INSERT INTO BUS_ROUTE Values ("UW/Cascadia Campus", "Redmond TC (to Downtown Seattle)", "931", 124);
INSERT INTO BUS_ROUTE Values ("Redmond TC (to Downtown Seattle)", "UW/Cascadia Campus", "931", 124);
INSERT INTO BUS_ROUTE Values ("Auburn P&R", "Boeing Everett", "952", 124);
INSERT INTO BUS_ROUTE Values ("Boeing Everett", "Auburn P&R", "952", 124);
INSERT INTO BUS_ROUTE Values ("Bear Creek P&R", "Lakeside (Haller Lake)", "982", 127);
INSERT INTO BUS_ROUTE Values ("Lakeside (Haller Lake)", "Bear Creek P&R", "982", 127);
INSERT INTO BUS_ROUTE Values ("Houghton P&R", "Lakeside (Haller Lake)", "986", 127);
INSERT INTO BUS_ROUTE Values ("Lakeside (Haller Lake)", "Houghton P&R", "986", 127);
INSERT INTO BUS_ROUTE Values ("Rainier Beach", "Lakeside (Haller Lake)", "987", 127);
INSERT INTO BUS_ROUTE Values ("Lakeside (Haller Lake)", "Rainier Beach", "987", 127);
INSERT INTO BUS_ROUTE Values ("Madrona", "Lakeside (Haller Lake)", "988", 127);
INSERT INTO BUS_ROUTE Values ("Lakeside (Haller Lake)", "Madrona", "988", 127);
INSERT INTO BUS_ROUTE Values ("Factoria", "Evergreen School", "989", 127);
INSERT INTO BUS_ROUTE Values ("Evergreen School", "Factoria", "989", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Lakeside (Haller Lake)", "994", 127);
INSERT INTO BUS_ROUTE Values ("Lakeside (Haller Lake)", "Downtown Seattle", "994", 127);
INSERT INTO BUS_ROUTE Values ("Laurelhurst", "Lakeside School", "995", 127);
INSERT INTO BUS_ROUTE Values ("Lakeside School", "Laurelhurst", "995", 127);