INSERT INTO BUS_ROUTE Values ("Federal Way TC", "Tukwila International Blvd Link Station", "671", 127);
INSERT INTO BUS_ROUTE Values ("Tukwila International Blvd Link Station", "Federal Way TC", "671", 127);
INSERT INTO BUS_ROUTE Values ("Bellevue TC", "Redmond TC", "672", 127);
INSERT INTO BUS_ROUTE Values ("Redmond TC", "Bellevue TC", "672", 127);
INSERT INTO BUS_ROUTE Values ("Westwood Village", "South Lake Union", "673", 127);
INSERT INTO BUS_ROUTE Values ("South Lake Union", "Westwood Village", "673", 127);
INSERT INTO BUS_ROUTE Values ("Crown Hill", "Downtown Seattle", "674", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Crown Hill", "674", 127);
INSERT INTO BUS_ROUTE Values ("Aurora Village", "Downtown Seattle", "675", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Aurora Village", "675", 127);
INSERT INTO BUS_ROUTE Values ("Burien", "The Landing", "676", 127);
INSERT INTO BUS_ROUTE Values ("The Landing", "Burien", "676", 127);
INSERT INTO BUS_ROUTE Values ("Kinnear", "Downtown Seattle", "1", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Kinnear", "1", 127);
INSERT INTO BUS_ROUTE Values ("Seattle Pacific", "Madrona Park", "2", 127);
INSERT INTO BUS_ROUTE Values ("Madrona Park", "Seattle Pacific", "2", 127);
INSERT INTO BUS_ROUTE Values ("Seattle Pacific University", "Madrona, Judkins Park", "3", 127);
INSERT INTO BUS_ROUTE Values ("Madrona, Judkins Park", "Seattle Pacific University", "3", 127);
INSERT INTO BUS_ROUTE Values ("Shoreline CC", "Downtown Seattle", "5", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Shoreline CC", "5", 127);
INSERT INTO BUS_ROUTE Values ("Prentice Street/Rainier Beach", "Downtown Seattle", "7", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Prentice Street/Rainier Beach", "7", 127);
INSERT INTO BUS_ROUTE Values ("Seattle Center", "Mt Baker TC", "8", 127);
INSERT INTO BUS_ROUTE Values ("Mt Baker TC", "Seattle Center", "8", 127);
INSERT INTO BUS_ROUTE Values ("Rainier Beach", "Broadway", "9", 124);
INSERT INTO BUS_ROUTE Values ("Broadway", "Rainier Beach", "9", 124);
INSERT INTO BUS_ROUTE Values ("Capitol Hill", "Downtown Seattle", "10", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Capitol Hill", "10", 127);
INSERT INTO BUS_ROUTE Values ("Madison Park", "Downtown Seattle", "11", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Madison Park", "11", 127);
INSERT INTO BUS_ROUTE Values ("Interlaken Park", "Downtown Seattle", "12", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Interlaken Park", "12", 127);
INSERT INTO BUS_ROUTE Values ("Seattle Pacific", "Madrona Park", "13", 127);
INSERT INTO BUS_ROUTE Values ("Madrona Park", "Seattle Pacific", "13", 127);
INSERT INTO BUS_ROUTE Values ("Mount Baker", "Downtown Seattle", "14", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Mount Baker", "14", 127);
INSERT INTO BUS_ROUTE Values ("Blue Ridge", "Downtown Seattle", "15", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Blue Ridge", "15", 124);
INSERT INTO BUS_ROUTE Values ("Sunset Hill", "Downtown Seattle", "17", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Sunset Hill", "17", 124);
INSERT INTO BUS_ROUTE Values ("North Beach", "Downtown Seattle", "18", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "North Beach", "18", 124);
INSERT INTO BUS_ROUTE Values ("West Magnolia", "Downtown Seattle", "19", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "West Magnolia", "19", 124);
INSERT INTO BUS_ROUTE Values ("Westwood Village", "Downtown Seattle", "21", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Westwood Village", "21", 127);
INSERT INTO BUS_ROUTE Values ("Arbor Heights", "Alaska Junction", "22", 127);
INSERT INTO BUS_ROUTE Values ("Alaska Junction", "Arbor Heights", "22", 127);
INSERT INTO BUS_ROUTE Values ("West Magnolia", "Downtown Seattle", "24", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "West Magnolia", "24", 127);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "Downtown Seattle", "26", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Northgate TC", "26", 127);
INSERT INTO BUS_ROUTE Values ("Colman Park", "Downtown Seattle", "27", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Colman Park", "27", 127);
INSERT INTO BUS_ROUTE Values ("Carkeek Park/Broadview", "Downtown Seattle", "28", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Carkeek Park/Broadview", "28", 127);
INSERT INTO BUS_ROUTE Values ("Ballard", "Downtown Seattle", "29", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Ballard", "29", 124);
INSERT INTO BUS_ROUTE Values ("Seattle Center Magnolia", "University District", "31", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Seattle Center Magnolia", "31", 127);
INSERT INTO BUS_ROUTE Values ("Discovery Park", "Downtown Seattle", "33", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Discovery Park", "33", 127);
INSERT INTO BUS_ROUTE Values ("Othello Station", "Downtown Seattle", "36", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Othello Station", "36", 127);
INSERT INTO BUS_ROUTE Values ("Alaska Junction", "Downtown Seattle", "37", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Alaska Junction", "37", 124);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "Downtown Seattle", "40", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Northgate TC", "40", 127);
INSERT INTO BUS_ROUTE Values ("Lake City", "Downtown Seattle", "41", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Lake City", "41", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Capitol Hill Downtown Seattle", "43", 127);
INSERT INTO BUS_ROUTE Values ("Capitol Hill Downtown Seattle", "University District", "43", 127);
INSERT INTO BUS_ROUTE Values ("Ballard", "UW Station", "44", 127);
INSERT INTO BUS_ROUTE Values ("UW Station", "Ballard", "44", 127);
INSERT INTO BUS_ROUTE Values ("Loyal Heights", "University District", "45", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Loyal Heights", "45", 127);
INSERT INTO BUS_ROUTE Values ("Summit", "Downtown Seattle", "47", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Summit", "47", 127);
INSERT INTO BUS_ROUTE Values ("Mt Baker TC", "University District", "48", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Mt Baker TC", "48", 127);
INSERT INTO BUS_ROUTE Values ("University District", "Downtown Seattle", "49", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "University District", "49", 127);
INSERT INTO BUS_ROUTE Values ("Othello Station", "Alki", "50", 127);
INSERT INTO BUS_ROUTE Values ("Alki", "Othello Station", "50", 127);
INSERT INTO BUS_ROUTE Values ("Admiral District", "Downtown Seattle", "55", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Admiral District", "55", 124);
INSERT INTO BUS_ROUTE Values ("Alki/Alaska Junction", "Downtown Seattle", "56", 124);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Alki/Alaska Junction", "56", 124);
INSERT INTO BUS_ROUTE Values ("Westwood Village", "Broadway", "60", 127);
INSERT INTO BUS_ROUTE Values ("Broadway", "Westwood Village", "60", 127);
INSERT INTO BUS_ROUTE Values ("Sand Point", "Downtown Seattle", "62", 127);
INSERT INTO BUS_ROUTE Values ("Downtown Seattle", "Sand Point", "62", 127);
INSERT INTO BUS_ROUTE Values ("Northgate TC", "Cherry Hill", "63", 124);