INSERT INTO BUS_STOP Values (80438, "Federal Way Transit Center Bay 8", "S 317th St & 23rd Ave S");
INSERT INTO BUS_STOP Values (60800, "Pacific Hwy S & Kent Des Moines Rd", "Pacific Hwy S & Kent Des Moines Rd");
INSERT INTO BUS_STOP Values (60900, "SeaTac International Airport", "Int'l Blvd & S 176th St");
INSERT INTO BUS_STOP Values (60921, "Tukwila Int'l Blvd Station Bay 1", "Tukwila Int'l Blvd & S 154th St");
INSERT INTO BUS_STOP Values (50480, "Pacific Hwy S & Kent", "Des Moines Rd");
INSERT INTO BUS_STOP Values (68003, "Bellevue Transit Center Bay 3", "NE 6th St & 108th Ave NE");
INSERT INTO BUS_STOP Values (68498, "Overlake Transit Center Bay 8", "156th Ave NE & NE 40th St");
INSERT INTO BUS_STOP Values (73350, "148th Ave NE & NE 51st St", "148th Ave NE & NE 51st St");
INSERT INTO BUS_STOP Values (73227, "Redmond Transit Center Bay 1", "161st Ave NE & NE 83rd St");
INSERT INTO BUS_STOP Values (22557, "Westwood Village", "SW Barton St & 26th Ave SW");
INSERT INTO BUS_STOP Values (19670, "Fauntleroy Ferry Terminal", "Fauntleroy Way SW & SW Barton St");
INSERT INTO BUS_STOP Values (19862, "Alaska Junction", "SW Alaska St & California Ave");
INSERT INTO BUS_STOP Values (590, "Downtown Seattle", "3rd Ave & Pine St");
INSERT INTO BUS_STOP Values (10325, "South Lake Union", "Fairview Ave N & Valley St");
INSERT INTO BUS_STOP Values (28680, "Crown Hill", "NW 100th Pl & 7th Ave NW");
INSERT INTO BUS_STOP Values (13721, "Ballard", "15th Ave NW & NW Market St");
INSERT INTO BUS_STOP Values (2672, "Uptown", "Queen Anne Ave N & W Mercer St");
INSERT INTO BUS_STOP Values (16100, "Aurora Village Transit Center Bay 10", "Ashworth Ave N & N 200th St");
INSERT INTO BUS_STOP Values (6950, "Bitter Lake", "Aurora Ave N & N 145th St");
INSERT INTO BUS_STOP Values (7160, "Aurora Ave N & N 85th St", "Aurora Ave N & N 85th St");
INSERT INTO BUS_STOP Values (75408, "Aurora Ave N & N 46th St", "Aurora Ave N & N 46th St");
INSERT INTO BUS_STOP Values (52306, "Burien Transit  Center Bay 6", "Transit Roadway & SW 148th St");
INSERT INTO BUS_STOP Values (60922, "LINK LIGHT RAIL", "Tukwila Int'l Blvd Station");
INSERT INTO BUS_STOP Values (59310, "Southcenter Mall", "Andover Park W & Baker Blvd");
INSERT INTO BUS_STOP Values (59882, "SOUNDER", "Tukwila Station");
INSERT INTO BUS_STOP Values (46477, "Renton Transit Center  Bay 2", "S 2nd St &  Burnett Ave S");
INSERT INTO BUS_STOP Values (46505, "The Landing", "N 10th St & Garden Ave N");
INSERT INTO BUS_STOP Values (2010, "Kinnear", "10th Ave W & W Fulton St");
INSERT INTO BUS_STOP Values (2332, "Seattle Center", "1st Ave N & John St");
INSERT INTO BUS_STOP Values (80777, "ROUTE 2", "West Queen Anne");
INSERT INTO BUS_STOP Values (5492, "Shoreline Community College", "Shoreline Community College");
INSERT INTO BUS_STOP Values (5550, "Greenwood Ave N & N 145th S", "Greenwood Ave N & N 145th S");
INSERT INTO BUS_STOP Values (5710, "Greenwood Ave N & Holman Rd N", "Greenwood Ave N & Holman Rd N");
INSERT INTO BUS_STOP Values (5790, "Greenwood Ave N & N 85th St", "Greenwood Ave N & N 85th St");
INSERT INTO BUS_STOP Values (5980, "Fremont", "Phinney Ave N & N 46th St");
INSERT INTO BUS_STOP Values (6710, "Greenwood Ave N & N 103rd St", "Greenwood Ave N & N 103rd St");
INSERT INTO BUS_STOP Values (6880, "Greenwood Ave N & N 145th St", "Greenwood Ave N & N 145th St");
INSERT INTO BUS_STOP Values (31137, "Rainier Beach", "Eastbound on S Henderson St at Rainier Ave S");
INSERT INTO BUS_STOP Values (8330, "Columbia City", "Rainier Ave S & S Genesee St");
INSERT INTO BUS_STOP Values (3600, "S Jackson St & 12th Ave S", "S Jackson St & 12th Ave S");
INSERT INTO BUS_STOP Values (7950, "Prentice St", "62nd Ave S & S Prentice St");
INSERT INTO BUS_STOP Values (55583, "Rainier Beach Station", "ML King Jr Way S & S Henderson St");
INSERT INTO BUS_STOP Values (8440, "Rainier Ave S & S Walker St", "Rainier Ave S & S Walker St");
INSERT INTO BUS_STOP Values (11012, "Broadway", "10th Ave E & E Aloha St");
INSERT INTO BUS_STOP Values (8540, "12th Ave S & S Jackson St", "12th Ave S & S Jackson St");
INSERT INTO BUS_STOP Values (11370, "Capitol Hill", "15th Ave E & E Galer St");
INSERT INTO BUS_STOP Values (29264, "E Olive Way & Broadway", "E Olive Way & Broadway");
INSERT INTO BUS_STOP Values (11132, "Pike St & Boren Ave", "Pike St & Boren Ave");
INSERT INTO BUS_STOP Values (29270, "E John St & Broadway", "E John St & Broadway");
INSERT INTO BUS_STOP Values (12210, "Madison Park", "E McGilvra St & 42nd Ave E");
INSERT INTO BUS_STOP Values (12350, "E Madison St & 23rd Ave E", "E Madison St & 23rd Ave E");
INSERT INTO BUS_STOP Values (11150, "E Pine St & Broadway", "E Pine St & Broadway");
INSERT INTO BUS_STOP Values (13200, "Interlaken Park", "19th Ave E & E Galer St");
INSERT INTO BUS_STOP Values (13282, "First Hill", "E Madison St & Broadway");
INSERT INTO BUS_STOP Values (11690, "Mt Baker", "Mt Rainier Dr S & S Hanford St");
INSERT INTO BUS_STOP Values (8403, "Mt Baker Transit Center Bay 3", "Rainier Ave S & S Forest St");
INSERT INTO BUS_STOP Values (11910, "23rd Ave S & S Jackson St", "23rd Ave S & S Jackson St");
INSERT INTO BUS_STOP Values (12010, "S Jackson St & 23rd Ave S", "S Jackson St & 23rd Ave S");
INSERT INTO BUS_STOP Values (20530, "West Magnolia", "W Emerson St & Magnolia Blvd W");
INSERT INTO BUS_STOP Values (20700, "Central Magnolia", "28th Ave W & W Blaine St");
INSERT INTO BUS_STOP Values (22264, "35th Ave SW & SW Roxbury St (Southbound)", "35th Ave SW & SW Roxbury St (Southbound)");
INSERT INTO BUS_STOP Values (39443, "Gatewood", "41st Ave SW & SW Thistle St");
INSERT INTO BUS_STOP Values (27175, "Colman Park", "36th Ave S & S Atlantic St");
INSERT INTO BUS_STOP Values (27350, "E Yesler Way & 23rd Ave", "E Yesler Way & 23rd Ave");
INSERT INTO BUS_STOP Values (1370, "E Yesler Way & 3rd Ave", "E Yesler Way & 3rd Ave");
INSERT INTO BUS_STOP Values (31140, "Discovery Park", "Illinois Ave & Texas Way");
INSERT INTO BUS_STOP Values (31350, "Magnolia", "Thorndyke Ave W & W Blaine St");
INSERT INTO BUS_STOP Values (45649, "Othello Station", "S Myrtle St & 39th  Ave S");
INSERT INTO BUS_STOP Values (30340, "Beacon  Hill", "Beacon Ave S & S Myrtle St");
INSERT INTO BUS_STOP Values (3380, "Jefferson Park", "Beacon Ave S & S Columbian Way");
INSERT INTO BUS_STOP Values (3470, "Beacon  Hill Station", "Beacon Ave S & S Lander St");
INSERT INTO BUS_STOP Values (1530, "S Jackson St & 5th Ave S", "S Jackson St & 5th Ave S");
INSERT INTO BUS_STOP Values (46092, "Beacon Hill", "S Myrtle St & Beacon Ave S");
INSERT INTO BUS_STOP Values (22850, "SW Alaska St & 35th Ave SW", "SW Alaska St & 35th Ave SW");
INSERT INTO BUS_STOP Values (32011, "Alaska Junction Bay 4", "44th Ave SW & SW Alaska St");
INSERT INTO BUS_STOP Values (32398, "48th Ave SW & Beach Dr SW", "48th Ave SW & Beach Dr SW");
INSERT INTO BUS_STOP Values (14960, "Alki", "Alki Ave SW & 61st Ave SW");
INSERT INTO BUS_STOP Values (15140, "26th Ave SW & SW Spokane St", "26th Ave SW & SW Spokane St");
INSERT INTO BUS_STOP Values (15190, "1st Ave S & S Spokane St", "1st Ave S & S Spokane St");
INSERT INTO BUS_STOP Values (26641, "Westlake Ave N & Mercer St", "Westlake Ave N & Mercer St");
INSERT INTO BUS_STOP Values (35297, "Northgate Transit Center Bay 6", "Transit Center Roadway & NE 103rd St");
INSERT INTO BUS_STOP Values (40032, "N 105th St & Aurora Ave N", "N 105th St & Aurora Ave N");
INSERT INTO BUS_STOP Values (40068, "N Northgate Way & Aurora Ave N", "N Northgate Way & Aurora Ave N");
INSERT INTO BUS_STOP Values (23170, "5th Ave NE & NE 125th St", "5th Ave NE & NE 125th St");
INSERT INTO BUS_STOP Values (35295, "Northgate Transit Center Bay 5", "NE 103rd St & Transit Roadway");
INSERT INTO BUS_STOP Values (455, "Downtown Seattle Tunnel", "University St Station Bay C");
INSERT INTO BUS_STOP Values (38653, "Lake City", "NE 130th St & 35th Ave NE");
INSERT INTO BUS_STOP Values (29225, "Phinney Ridge", "N 46th St & Phinney Ave N");
INSERT INTO BUS_STOP Values (29231, "Wallingford", "N 45th St & Stone Way N");
INSERT INTO BUS_STOP Values (10911, "University District", "NE 45th St & University Way NE");
INSERT INTO BUS_STOP Values (29243, "UW Station", "NE Pacific Pl & NE Pacific St");
INSERT INTO BUS_STOP Values (35530, "Loyal Heights", "Loyal Way NW & NW 85th St");
INSERT INTO BUS_STOP Values (5330, "Greenwood", "N 85th St & Greenwood Ave N");
INSERT INTO BUS_STOP Values (16440, "NE 65th St & Roosevelt Way NE", "NE 65th St & Roosevelt Way NE");
INSERT INTO BUS_STOP Values (13390, "Summit", "Bellevue Ave E & Bellevue Pl E");
INSERT INTO BUS_STOP Values (35825, "Central District", "23rd Ave E & E  John St");
INSERT INTO BUS_STOP Values (25751, "Montlake Station", "On Montlake Blvd at SR");
INSERT INTO BUS_STOP Values (10916, "Harvard Ave E & Eastlake Ave E", "Harvard Ave E & Eastlake Ave E");
INSERT INTO BUS_STOP Values (15060, "Admiral District", "SW Admiral Way & California Ave SW");
INSERT INTO BUS_STOP Values (39464, "Genesee Hill", "55th Ave SW & SW Dakota St");
INSERT INTO BUS_STOP Values (32150, "South Park", "14th Ave S & S Cloverdale St");
INSERT INTO BUS_STOP Values (41740, "Georgetown", "13th Ave S & S Bailey St");
INSERT INTO BUS_STOP Values (36960, "Green Lake P&R", "NE 65th St & Oswego Pl NE");
INSERT INTO BUS_STOP Values (12980, "Cherry Hill", "E Jefferson St & 17th Ave");
INSERT INTO BUS_STOP Values (35324, "Northgate Transit Center", "Bay 2");
INSERT INTO BUS_STOP Values (82230, "Jackson Park", "NE 145th St & 15th Ave NE");
INSERT INTO BUS_STOP Values (25000, "Wedgwood", "35th Ave NE & NE 94th St");
INSERT INTO BUS_STOP Values (37940, "35th Ave NE & NE 65th St", "35th Ave NE & NE 65th St");
INSERT INTO BUS_STOP Values (5419, "I", "5 & NE 45th St");
INSERT INTO BUS_STOP Values (16419, "Green Lake", "8th Ave NE & NE 64th St");
INSERT INTO BUS_STOP Values (9978, "Children's Hospital", "Sand Point Way NE & 40th Ave NE");
INSERT INTO BUS_STOP Values (9575, "NE Campus Pkwy & University Way NE", "NE Campus Pkwy & University Way NE");
INSERT INTO BUS_STOP Values (9141, "Eastlake Ave E & Harvard Ave E", "Eastlake Ave E & Harvard Ave E");
INSERT INTO BUS_STOP Values (10225, "Fairview Ave N & Thomas St", "Fairview Ave N & Thomas St");
INSERT INTO BUS_STOP Values (10280, "Fairview Ave & Denny Way", "Fairview Ave & Denny Way");
INSERT INTO BUS_STOP Values (10640, "Sand Point", "Sand Point Way NE & NE 74th St");
INSERT INTO BUS_STOP Values (10030, "Ravenna", "NE 55th St & 35th Ave NE");
INSERT INTO BUS_STOP Values (5402, "NE 42nd St & 8th Ave NE", "NE 42nd St & 8th Ave NE");
INSERT INTO BUS_STOP Values (75406, "U of W Campus", "HUB");
INSERT INTO BUS_STOP Values (29915, "Mary Gates Memorial Dr & NE 45th St", "Mary Gates Memorial Dr & NE 45th St");
INSERT INTO BUS_STOP Values (55938, "South Renton Park & Ride Bay 2", "Lake Ave S & Shattuck Ave S");
INSERT INTO BUS_STOP Values (45301, "Renton Transit Center Bay 5", "Burnett Ave S & S 3rd St");
INSERT INTO BUS_STOP Values (79560, "Martin Luther King Jr Way S & S 129th St", "Martin Luther King Jr Way S & S 129th St");
INSERT INTO BUS_STOP Values (99252, "SODO Busway & S Spokane St", "SODO Busway & S Spokane St");
INSERT INTO BUS_STOP Values (59839, "South Renton Park & Ride Bay 4", "Lake Ave S & Shattuck Av S");
INSERT INTO BUS_STOP Values (60137, "Fairwood", "140th Way SE & SE 158th St");
INSERT INTO BUS_STOP Values (60185, "140th Ave SE & Petrovitsky Rd", "140th Ave SE & Petrovitsky Rd");
INSERT INTO BUS_STOP Values (59720, "Edmonds Ave SE & Puget Dr SE", "Edmonds Ave SE & Puget Dr SE");
INSERT INTO BUS_STOP Values (54842, "Renton Highlands", "Harrington Ave NE & NE 16th St");
INSERT INTO BUS_STOP Values (54150, "NE 4th St & Union Ave NE", "NE 4th St & Union Ave NE");
INSERT INTO BUS_STOP Values (55050, "Skyway", "Renton Ave S & S 126th St");
INSERT INTO BUS_STOP Values (55651, "ML King Jr Way S & S Othello St", "ML King Jr Way S & S Othello St");
INSERT INTO BUS_STOP Values (843, "Chinatown/Int'l District", "5th Ave S & S Jackson St");
INSERT INTO BUS_STOP Values (8681, "Rainier Ave S & S Stevens St", "Rainier Ave S & S Stevens St");
INSERT INTO BUS_STOP Values (85170, "Shorewood", "26th Ave SW & SW 116th St");
INSERT INTO BUS_STOP Values (21080, "White Center", "15th Ave SW & SW Roxbury St");
INSERT INTO BUS_STOP Values (21141, "Olson", "Myers Park & Ride");
INSERT INTO BUS_STOP Values (40802, "Federal Center South", "E Marginal Way S & S Hudson St");
INSERT INTO BUS_STOP Values (21450, "Delridge", "Delridge Way SW & SW Myrtle St");
INSERT INTO BUS_STOP Values (51520, "Ambaum Blvd SW & SW 128th St", "Ambaum Blvd SW & SW 128th St");
INSERT INTO BUS_STOP Values (47260, "Highline College", "Highline College");
INSERT INTO BUS_STOP Values (47390, "Des Moines", "S 223rd St & Marine View Dr S");
INSERT INTO BUS_STOP Values (47570, "1st Ave S & SW Normandy Rd", "1st Ave S & SW Normandy Rd");
INSERT INTO BUS_STOP Values (49110, "S 200th St & Des Moines Memorial Dr S", "S 200th St & Des Moines Memorial Dr S");
INSERT INTO BUS_STOP Values (47654, "Burien", "SW 152nd St & 6th Ave SW");
INSERT INTO BUS_STOP Values (53660, "Gregory Heights", "14th Ave SW & SW 160th St");
INSERT INTO BUS_STOP Values (31610, "Boeing Industrial", "lnternational Blvd & S 112th St");
INSERT INTO BUS_STOP Values (79562, "Boeing Plant 2", "East Marginal Way S & 16th Ave S");
INSERT INTO BUS_STOP Values (30635, "4th Ave S & S Royal Brougham Way", "4th Ave S & S Royal Brougham Way");
INSERT INTO BUS_STOP Values (21833, "6th Ave S & S Royal Brougham Way", "6th Ave S & S Royal Brougham Way");
INSERT INTO BUS_STOP Values (36525, "South Seattle College", "At On");
INSERT INTO BUS_STOP Values (21620, "West Seattle", "Delridge Way SW & SW Andover St");
INSERT INTO BUS_STOP Values (31811, "Alaska Junction Bay 2", "East on SW Alaska St at 44th Ave SW");
INSERT INTO BUS_STOP Values (22160, "SW Orchard St & Delridge Way SW", "SW Orchard St & Delridge Way SW");
INSERT INTO BUS_STOP Values (41121, "HMC Specialty Campus", "Military Rd S & S 128th St");
INSERT INTO BUS_STOP Values (52353, "Black Diamond", "Baker St & 3rd Ave");
INSERT INTO BUS_STOP Values (99294, "Maple Valley Rd & Kent Kangley Rd", "Maple Valley Rd & Kent Kangley Rd");
INSERT INTO BUS_STOP Values (99430, "Maple Valley Park & Ride", "SR");
INSERT INTO BUS_STOP Values (99390, "Maple Valley Hwy & Cedar Grove Rd", "Maple Valley Hwy & Cedar Grove Rd");
INSERT INTO BUS_STOP Values (99330, "Maple Valley Hwy & 149th Ave SE", "Maple Valley Hwy & 149th Ave SE");
INSERT INTO BUS_STOP Values (46479, "Renton Transit Center Bay 4 or 7", "S 2nd St & Burnett Ave S");
INSERT INTO BUS_STOP Values (57453, "Kent Station Bay 3", "Railroad Ave N & Pioneer St");
INSERT INTO BUS_STOP Values (60373, "Lind Ave SW & SW 43rd St", "Lind Ave SW & SW 43rd St");
INSERT INTO BUS_STOP Values (59904, "S Renton Park & Ride Bay 3", "S Grady Way & Shattuck Ave S");
INSERT INTO BUS_STOP Values (45305, "Renton Transit Center Bay 7", "S 3rd St & Burnett Ave S");
INSERT INTO BUS_STOP Values (60902, "Sea", "Tac Airport Station");
INSERT INTO BUS_STOP Values (60453, "Lake Meridian Park & Ride", "132nd Ave SE & SE 272nd St");
INSERT INTO BUS_STOP Values (57124, "North Meridian Park", "116th Ave SE & SE 240th St");
INSERT INTO BUS_STOP Values (85842, "Kent East Hill", "SE 208th St & 108th Ave SE");
INSERT INTO BUS_STOP Values (58060, "S 212th St & 42nd Ave S", "S 212th St & 42nd Ave S");
INSERT INTO BUS_STOP Values (42576, "Twin Lakes Park & Ride", "21st Ave SW & SW 344th St");
INSERT INTO BUS_STOP Values (57806, "Outlet Collection Seattle", "15th St SW & Market St SW");
INSERT INTO BUS_STOP Values (57773, "Auburn Station Bay 1", "Transit Roadway & 1st St SW");
INSERT INTO BUS_STOP Values (59200, "M St NE & 4th St NE", "M St NE & 4th St NE");
INSERT INTO BUS_STOP Values (59282, "Green River College", "SE 320th St & 122nd Ave SE");
INSERT INTO BUS_STOP Values (57775, "Auburn Station Bay 3", "Transit Roadway & 2nd St SW");
INSERT INTO BUS_STOP Values (85964, "Camelot", "45th Pl S & S 288th St");
INSERT INTO BUS_STOP Values (47973, "Star Lake", "On S 272nd St at I");
INSERT INTO BUS_STOP Values (50703, "Military Rd S & Reith Rd", "Military Rd S & Reith Rd");
INSERT INTO BUS_STOP Values (60747, "Redondo Heights Park & Ride", "Pacific Hwy S & S 276th St");
INSERT INTO BUS_STOP Values (47990, "Star Lake Freeway Station", "I");
INSERT INTO BUS_STOP Values (21945, "Kent", "Des Moines Park & Ride");
INSERT INTO BUS_STOP Values (390, "2nd Ave Ext S & S Jackson St", "2nd Ave Ext S & S Jackson St");
INSERT INTO BUS_STOP Values (250, "2nd Ave & Bell St", "2nd Ave & Bell St");
INSERT INTO BUS_STOP Values (80710, "Tukwila Park & Ride", "Interurban Ave S & 52nd Ave S");
INSERT INTO BUS_STOP Values (41981, "Virginia Mason", "9th Ave & Spring St");
INSERT INTO BUS_STOP Values (11085, "Boren Ave & Madison St", "Boren Ave & Madison St");
INSERT INTO BUS_STOP Values (80432, "Federal Way Transit Center Bay 2", "23rd Ave S & S 317th St");
INSERT INTO BUS_STOP Values (58782, "Kent Des", "Moines Freeway Station");
INSERT INTO BUS_STOP Values (29247, "NE Pacific St & NE Pacific Pl", "NE Pacific St & NE Pacific Pl");
INSERT INTO BUS_STOP Values (64305, "ROUTE 208", "North Bend");
INSERT INTO BUS_STOP Values (64555, "ST 554", "Issaquah Transit Center Bay 2");
INSERT INTO BUS_STOP Values (67014, "Eastgate Park & Ride Bay 1", "SE Eastgate Way & 140th Ave SE");
INSERT INTO BUS_STOP Values (620, "4th Ave S & S Jackson St", "4th Ave S & S Jackson St");
INSERT INTO BUS_STOP Values (375, "2nd Ave Ext S & Yesler Way", "2nd Ave Ext S & Yesler Way");
INSERT INTO BUS_STOP Values (62329, "Redmond", "NE Redmond Way & 185th Ave NE");
INSERT INTO BUS_STOP Values (81684, "South Sammamish Park & Ride", "SE Pine Lake Rd & 228th Ave SE");
INSERT INTO BUS_STOP Values (64561, "Issaquah Highlands Park & Ride Bay 4", "Highlands Dr NE & 9th Ave NE");
INSERT INTO BUS_STOP Values (64140, "Mercer Island Park & Ride", "N Mercer Way & 80th Ave SE");
INSERT INTO BUS_STOP Values (81755, "Bear Creek Park & Ride", "178th Pl NE & NE 78th Pl");
INSERT INTO BUS_STOP Values (79874, "Factoria", "SE 36th St & 136th Pl SE");
INSERT INTO BUS_STOP Values (64481, "North Issaquah", "220th Ave SE & SE 56th St");
INSERT INTO BUS_STOP Values (74041, "Education Hill", "NE 109th St & Woodinville");
INSERT INTO BUS_STOP Values (73130, "148th Ave NE & Old Redmond Rd", "148th Ave NE & Old Redmond Rd");
INSERT INTO BUS_STOP Values (68200, "Crossroads", "156th Ave NE & NE 8th St");
INSERT INTO BUS_STOP Values (66880, "164th Ave SE & SE 14th St", "164th Ave SE & SE 14th St");
INSERT INTO BUS_STOP Values (71960, "Redmond Transit Center Bay 1 or 5", "NE 83rd St & 161st Ave NE");
INSERT INTO BUS_STOP Values (68803, "Duvall", "Brown Ave NE & NE Richardson St");
INSERT INTO BUS_STOP Values (72521, "Redmond Ridge", "Cedar Park NE & NE Marketplace Dr");
INSERT INTO BUS_STOP Values (68390, "Overlake", "156th Ave NE & NE 24th St");
INSERT INTO BUS_STOP Values (69028, "NE 10th St & 116th Ave NE", "NE 10th St & 116th Ave NE");
INSERT INTO BUS_STOP Values (85630, "Bellevue Transit Center Bay 1", "108th Ave NE & NE 6th St");
INSERT INTO BUS_STOP Values (72984, "Bellevue College", "Kelsey Creek Rd & Tye River Rd");
INSERT INTO BUS_STOP Values (84031, "Cottage Lake", "NE Woodinville");
INSERT INTO BUS_STOP Values (71850, "Avondale", "Avondale Rd NE & NE 116th St");
INSERT INTO BUS_STOP Values (75995, "Woodinville Park & Ride", "140th Ave NE & NE 179th St");
INSERT INTO BUS_STOP Values (82700, "Brickyard Park & Ride", "NE 160th St & I");
INSERT INTO BUS_STOP Values (84003, "Kingsgate", "132nd Ave NE  & NE 132nd St");
INSERT INTO BUS_STOP Values (74232, "Totem Lake Transit Center Bay 2", "NE 128th St & 120th Ave NE");
INSERT INTO BUS_STOP Values (70170, "Juanita", "98th Ave NE & NE 116th St");
INSERT INTO BUS_STOP Values (73818, "Kirkland Transit Center Bay 4", "3rd St & Park Lane");
INSERT INTO BUS_STOP Values (82716, "Houghton Freeway Station", "NE 70th Pl & I");
INSERT INTO BUS_STOP Values (82878, "Totem Lake Freeway Station", "NE 128th St & I");
INSERT INTO BUS_STOP Values (76305, "UW/Cascadia College", "Campus Way NE across from Bookstore");
INSERT INTO BUS_STOP Values (76021, "Bothell", "E Riverside Dr & 102nd Ave NE");
INSERT INTO BUS_STOP Values (80509, "NE 120th St & 132nd Ave NE", "NE 120th St & 132nd Ave NE");
INSERT INTO BUS_STOP Values (72314, "Houghton Park & Ride Bay 2", "116th Ave NE & NE 70th Pl");
INSERT INTO BUS_STOP Values (70820, "Wilburton Park & Ride", "SE 8th St & 114th Ave SE");
INSERT INTO BUS_STOP Values (65252, "Newcastle Way & Coal Creek Pkwy SE", "Newcastle Way & Coal Creek Pkwy SE");
INSERT INTO BUS_STOP Values (45219, "Renton Boeing", "Park Ave N & N 8th St");
INSERT INTO BUS_STOP Values (84292, "Bellevue Way SE & 112th Ave SE", "Bellevue Way SE & 112th Ave SE");
INSERT INTO BUS_STOP Values (74001, "Willows Rd NE & NE 116th St", "Willows Rd NE & NE 116th St");
INSERT INTO BUS_STOP Values (76302, "Bothell Park & Ride", "Woodinville Dr & Kaysner Way");
INSERT INTO BUS_STOP Values (76376, "Kenmore Park & Ride", "NE 181st St & 73rd Ave NE");
INSERT INTO BUS_STOP Values (69630, "84th Ave NE & NE 155th St", "84th Ave NE & NE 155th St");
INSERT INTO BUS_STOP Values (74721, "Kingsgate Park & Ride", "116th Way NE & NE 132nd St");
INSERT INTO BUS_STOP Values (74076, "Willows Rd & NE 124th St", "Willows Rd & NE 124th St");
INSERT INTO BUS_STOP Values (74074, "NE 124th St & Willows Rd", "NE 124th St & Willows Rd");
INSERT INTO BUS_STOP Values (72881, "Somerset School", "14100 Somerset Blvd SE");
INSERT INTO BUS_STOP Values (99751, "Woodridge Park & Ride", "123rd Ave SE & SE 20th Pl");
INSERT INTO BUS_STOP Values (64940, "Clyde Hill/Yarrow Point Freeway Station", "92nd Ave NE & SR");
INSERT INTO BUS_STOP Values (67015, "Eastgate Park & Ride Bay 2", "140th Ave SE & SE Eastgate Way");
INSERT INTO BUS_STOP Values (73950, "Rose Hill", "NE 85th St & 132nd Ave NE");
INSERT INTO BUS_STOP Values (71210, "West Lake Sammamish Pkwy NE & NE 24th St", "West Lake Sammamish Pkwy NE & NE 24th St");
INSERT INTO BUS_STOP Values (71328, "Overlake P&R", "152nd Ave NE & 2600 Crossing");
INSERT INTO BUS_STOP Values (74450, "South Kirkland P&R", "NE 38th Pl & 108th Ave NE");
INSERT INTO BUS_STOP Values (70310, "Brickyard P&R", "Juan");
INSERT INTO BUS_STOP Values (81456, "NE 144th St & 124th Ave NE", "NE 144th St & 124th Ave NE");
INSERT INTO BUS_STOP Values (81472, "119th Ave NE & NE 159th St", "119th Ave NE & NE 159th St");
INSERT INTO BUS_STOP Values (71355, "Evergreen Station", "On SR");
INSERT INTO BUS_STOP Values (74190, "124th Ave NE & NE 137th Pl", "124th Ave NE & NE 137th Pl");
INSERT INTO BUS_STOP Values (700, "4th Ave & Pike St", "4th Ave & Pike St");
INSERT INTO BUS_STOP Values (71341, "SR", "520 & NE 51st St");
INSERT INTO BUS_STOP Values (72329, "185th Ave NE & Redmond", "Fall City Rd");
INSERT INTO BUS_STOP Values (64592, "Issaquah Transit Center Bay 5", "Newport Way NW & 17th Ave NW");
INSERT INTO BUS_STOP Values (64465, "E Lake Sammamish Pkwy SE & SE 56th St", "E Lake Sammamish Pkwy SE & SE 56th St");
INSERT INTO BUS_STOP Values (64545, "Issaquah Highlands Park & Ride", "9th Ave NE & Highlands Dr NE");
INSERT INTO BUS_STOP Values (81665, "228th Ave NE & NE 8th St", "228th Ave NE & NE 8th St");
INSERT INTO BUS_STOP Values (68404, "Overlake Transit Center", "NE 40th St & 156th Ave NE");
INSERT INTO BUS_STOP Values (25752, "Montlake", "On Montlake Blvd at Shelby St");
INSERT INTO BUS_STOP Values (16101, "Aurora Village Transit Center Bay 1", "N 200th St & Ashworth Ave N");
INSERT INTO BUS_STOP Values (75730, "Shoreline Park & Ride", "Aurora Ave N & N 192nd St");
INSERT INTO BUS_STOP Values (77315, "Richmond Beach", "8th Ave NW & NW 205th St");
INSERT INTO BUS_STOP Values (75756, "Meridian Park", "N 175th St & Meridian Ave N");
INSERT INTO BUS_STOP Values (9271, "Eastlake", "Eastlake Ave E & Aloha St");
INSERT INTO BUS_STOP Values (81330, "Horizon View", "45th Ave NE & NE 203rd Pl");
INSERT INTO BUS_STOP Values (82097, "35th Ave NE & NE 195th St", "35th Ave NE & NE 195th St");
INSERT INTO BUS_STOP Values (76590, "Lake Forest Park", "Bothell Way NE & Ballinger Way NE");
INSERT INTO BUS_STOP Values (76660, "Lake City Way NE & NE 145th St", "Lake City Way NE & NE 145th St");
INSERT INTO BUS_STOP Values (76700, "Lake City Way", "Lake City Way NE & NE 130th St");
INSERT INTO BUS_STOP Values (16800, "Haller Lake", "Meridian Ave N & N 145th St");
INSERT INTO BUS_STOP Values (17010, "North Seattle College", "North Seattle College");
INSERT INTO BUS_STOP Values (75790, "Aurora Ave N & N 160th St", "Aurora Ave N & N 160th St");
INSERT INTO BUS_STOP Values (77630, "Fircrest", "15th Ave NE & NE 155th St");
INSERT INTO BUS_STOP Values (70702, "ROUTE 331", "3rd Ave NW & NW Richmond Beach Rd");
INSERT INTO BUS_STOP Values (76880, "ST 522", "Kenmore Park & Ride");
INSERT INTO BUS_STOP Values (85796, "Mount Si Senior Center", "Main Av S & W Park St");
INSERT INTO BUS_STOP Values (64333, "Snoqualmie", "Railroad Ave SE & SE Northern St");
INSERT INTO BUS_STOP Values (64413, "Snoqualmie Community Park & Ride", "SE Ridge St & Center Blvd SE");
INSERT INTO BUS_STOP Values (62370, "Mercer Village Shopping Center", "Mercer Village & SE 68th St");
INSERT INTO BUS_STOP Values (63340, "Mercer Island", "Island Crest Way & SE 46th St");
INSERT INTO BUS_STOP Values (53978, "Highline Medical Center", "Highline Medical Center");
INSERT INTO BUS_STOP Values (52302, "Burien Transit Center", "SW 148th St & 2nd Ave SW");
INSERT INTO BUS_STOP Values (6071, "Seacrest Park", "Harbor Ave SW at Seacrest Park");
INSERT INTO BUS_STOP Values (59604, "156th Ave SE & SE Fairwood Blvd", "156th Ave SE & SE Fairwood Blvd");
INSERT INTO BUS_STOP Values (60270, "116th Ave SE & SE 168th St", "116th Ave SE & SE 168th St");
INSERT INTO BUS_STOP Values (60360, "Valley Medical Center", "S Carr Rd & Talbot Rd S");
INSERT INTO BUS_STOP Values (58090, "S 180th St & Andover Park W", "S 180th St & Andover Park W");
INSERT INTO BUS_STOP Values (60442, "Southcenter", "Baker Blvd & Andover Park W");
INSERT INTO BUS_STOP Values (54920, "Edmonds Ave NE & NE 7th St", "Edmonds Ave NE & NE 7th St");
INSERT INTO BUS_STOP Values (46463, "Renton Transit Center Bay 10", "S 2nd Ave & Burnett Ave S");
INSERT INTO BUS_STOP Values (56570, "NE 7th St & Edmonds Ave NE", "NE 7th St & Edmonds Ave NE");
INSERT INTO BUS_STOP Values (58345, "The Outlet Collection Seattle", "Outlet Collection Dr at  Carousel Court");
INSERT INTO BUS_STOP Values (58300, "A St NE & 10th St NE", "A St NE & 10th St NE");
INSERT INTO BUS_STOP Values (58467, "North Auburn", "37th St NW & Auburn Way N");
INSERT INTO BUS_STOP Values (57776, "Auburn Station Bay 4", "Transit Rdwy & 1st St SW");
INSERT INTO BUS_STOP Values (57455, "Kent Station Bay 5", "Railroad Ave N & W Pioneer St");
INSERT INTO BUS_STOP Values (50621, "North Kent", "Boeing Access Rd & S 204th St");
INSERT INTO BUS_STOP Values (80013, "Riverview", "Riverview Blvd S  & S 212th St");
INSERT INTO BUS_STOP Values (80031, "Lakeside Blvd  E &  S 228th St", "Lakeside Blvd  E &  S 228th St");
INSERT INTO BUS_STOP Values (57861, "White River Junction", "A St SE & 41st St SE");
INSERT INTO BUS_STOP Values (81178, "Algona", "1st Ave S & Main St");
INSERT INTO BUS_STOP Values (57810, "C St SW & 15th St SW", "C St SW & 15th St SW");
INSERT INTO BUS_STOP Values (58348, "Aleshire Ave at GSA", "Aleshire Ave at GSA");
INSERT INTO BUS_STOP Values (74097, "DART 931", "English Hill");
INSERT INTO BUS_STOP Values (71954, "ROUTE 545", "Redmond Transit Center Bay 6");
INSERT INTO BUS_STOP Values (27540, "E Yesler Way & 18th Ave S", "E Yesler Way & 18th Ave S");
INSERT INTO BUS_STOP Values (43778, "Madison Valley", "MLK Jr Way E & E Alder St");
INSERT INTO BUS_STOP Values (25791, "University Village", "25th Ave NE & NE 47th St");
INSERT INTO BUS_STOP Values (25798, "University Prep", "25th Ave NE & NE 80th St");
INSERT INTO BUS_STOP Values (81294, "Lakeside School", "1st Ave NE & NE 140th St");
INSERT INTO BUS_STOP Values (82687, "Totem Lake", "Fwy Station On I");
INSERT INTO BUS_STOP Values (23390, "Roosevelt Way NE & NE 75th St", "Roosevelt Way NE & NE 75th St");
INSERT INTO BUS_STOP Values (34680, "Seward Park", "Seward Park Ave S & S Holly St");
INSERT INTO BUS_STOP Values (55875, "S Dearborn St & Corwin Pl S", "S Dearborn St & Corwin Pl S");
INSERT INTO BUS_STOP Values (27600, "Yesler Way & 28th Ave S", "Yesler Way & 28th Ave S");
INSERT INTO BUS_STOP Values (34930, "S Genesee St & Cascadia Ave S", "S Genesee St & Cascadia Ave S");
INSERT INTO BUS_STOP Values (3300, "Madrona", "Madrona Dr & 38th Ave");
INSERT INTO BUS_STOP Values (16330, "Evergreen School", "Meridian Ave N & N 150th St");
INSERT INTO BUS_STOP Values (29952, "Laurelhurst", "NE 45th St & 42nd Ave NE");
INSERT INTO BUS_STOP Values (37850, "View Ridge", "NE 65th St & 55th Ave NE");
INSERT INTO BUS_STOP Values (25200, "NE 45th St & Union Bay Pl NE", "NE 45th St & Union Bay Pl NE");