-- Insert park and rides
INSERT INTO PARK_AND_RIDE Values ("Auburn", "27225 Military Rd S", "All Saints Lutheran Church", 75, 50703);
INSERT INTO PARK_AND_RIDE Values ("Auburn", "A St SW and 1st St SW", "Auburn Park and Ride", 244, 57810);
INSERT INTO PARK_AND_RIDE Values ("Auburn", "A St SW and 1st St SW", "Auburn Garage at Auburn Station", 520, 57810);
INSERT INTO PARK_AND_RIDE Values ("Auburn", "A St SW and 1st St SW", "Auburn Surface Lot at Auburn Station", 113, 57810);
INSERT INTO PARK_AND_RIDE Values ("Auburn", "400 Lakeland Hills Way SE", "Family Life Center", 27, 76590);
INSERT INTO PARK_AND_RIDE Values ("Auburn", "1306 69th St SE", "Sunset Park", 10, 79874);
INSERT INTO PARK_AND_RIDE Values ("Auburn", "SR 18 and Auburn-Black Diamond Rd", "SR 18 and Auburn", 26, 73130);
INSERT INTO PARK_AND_RIDE Values ("Auburn", "W Valley Rd and Peasley Canyon Rd", "Peasley Canyon Park and Ride", 54, 99294);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "1221 148th Ave NE", "Bellevue Christian Reformed Church", 20, 74450);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "15318 SE Newport Way", "Eastgate Congregational Church", 20, 73818);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "148th Ave SE and SE 28th St", "St. Andrew's Lutheran Church", 50, 57124);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "119th Ave SE and SE 58th St", "Newport Hills Community Church", 37, 60270);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "Bellevue Way NE and NE 30th Pl", "St. Luke's Lutheran Church", 30, 84292);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "Richards Rd and SE 21st Pl", "Bellevue Foursquare Church", 50, 41121);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "Coal Creek Pkwy and Factoria Blvd", "Newport Covenant Church", 75, 59310);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "NE 8th St and 96th Ave NE", "Grace Lutheran Church", 50, 37850);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "156th Ave NE and NE 6th St", "Cross of Christ Lutheran Church", 50, 68200);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "140th Ave SE and SE 5th St", "Lake Hills Baptist Church", 50, 64481);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "156th Ave NE and Northup Way", "Overlake Park Presbyterian Church", 50, 68200);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "140th Ave NE and NE 6th Pl", "The Neighborhood Church", 50, 85630);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "I-405 and SE 8th St", "Wilburton Park and Ride", 186, 5419);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "104th Ave SE and SE 11th St", "Bellevue Church of Christ", 50, 66880);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "Bellevue Way SE and SE 16th St", "Enatai", 46, 84292);
INSERT INTO PARK_AND_RIDE Values ("Bellevue", "I-405 and 112th Pl SE", "Newport Hills Park and Ride", 275, 79874);
INSERT INTO PARK_AND_RIDE Values ("Black Diamond", "32523 3rd Ave", "Black Diamond Masonic Lodge", 30, 52353);
INSERT INTO PARK_AND_RIDE Values ("Bothell", "I-405 and NE 160th St", "Brickyard Road", 443, 5419);
INSERT INTO PARK_AND_RIDE Values ("Bothell", "Woodinville Dr and Kaysner Way", "Bothell Park and Ride", 220, 76302);
INSERT INTO PARK_AND_RIDE Values ("Burien", "1st Ave S and SW 166th St", "Burien Church of God", 20, 53660);
INSERT INTO PARK_AND_RIDE Values ("Burien", "SW 150th St and 4th Ave SW", "Burien Transit Center", 588, 47654);
INSERT INTO PARK_AND_RIDE Values ("Covington", "20730 SE 272nd St, near SR 516", "Cornerstone United Methodist Church", 20, 47973);
INSERT INTO PARK_AND_RIDE Values ("Duvall", "SR 203 and Woodinville-Duvall Rd", "Duvall Park and Ride", 49, 74041);
INSERT INTO PARK_AND_RIDE Values ("Enumclaw", "Farrelly St and Griffin Ave", "Sacred Heart Church", 40, 52353);
INSERT INTO PARK_AND_RIDE Values ("Enumclaw", "SE 436th St (SR 164) and 228th Ave SE", "Farmer's Park Park and Ride", 25, 85842);
INSERT INTO PARK_AND_RIDE Values ("Federal Way", "515 S 312th St", "St. Luke's Lutheran Church", 20, 80432);
INSERT INTO PARK_AND_RIDE Values ("Federal Way", "150 S 356th St", "Sunrise United Methodist Church", 25, 5419);
INSERT INTO PARK_AND_RIDE Values ("Federal Way", "S 320th St and 8th Ave S", "Our Savior's Baptist Church", 24, 85842);
INSERT INTO PARK_AND_RIDE Values ("Federal Way", "S 323rd St and 23rd Ave S", "Federal Way/S 320th St Park and Ride", 877, 80438);
INSERT INTO PARK_AND_RIDE Values ("Federal Way", "9th Ave S and S 348th St", "South Federal Way Park and Ride", 515, 80432);
INSERT INTO PARK_AND_RIDE Values ("Federal Way", "Pacific Hwy S at S 276th St", "Redondo Heights Park and Ride", 697, 60747);
INSERT INTO PARK_AND_RIDE Values ("Federal Way", "21st Ave SW and SW 344th", "Twin Lakes Park and Ride", 600, 42576);
INSERT INTO PARK_AND_RIDE Values ("Issaquah", "1675 Newport Way NW", "Tibbetts Lot", 170, 64592);
INSERT INTO PARK_AND_RIDE Values ("Issaquah", "12th Ave NW and Newport Way", "Tibbetts Valley Park Park and Ride", 27, 13721);
INSERT INTO PARK_AND_RIDE Values ("Issaquah", "SR 900 and Newport Way", "Issaquah Transit Center", 819, 64592);
INSERT INTO PARK_AND_RIDE Values ("Issaquah", "SE Klahanie Blvd and 244th PL SE", "Klahanie #1 Park and Ride", 30, 79874);
INSERT INTO PARK_AND_RIDE Values ("Issaquah", "SE Klahanie Dr SE and SE 40th St", "Klahanie #3 Park and Ride", 30, 57124);
INSERT INTO PARK_AND_RIDE Values ("Kenmore", "Bothell Way and 73rd Ave NE", "Kenmore Park and Ride", 606, 76376);
INSERT INTO PARK_AND_RIDE Values ("Kenmore", "Bothell Way NE and 75th Ave NE", "Kenmore Community Church", 15, 76590);
INSERT INTO PARK_AND_RIDE Values ("Kenmore", "NE 181st St and 62nd Ave NE", "The Vine Church", 75, 76376);
INSERT INTO PARK_AND_RIDE Values ("Kent", "22600 116th Ave SE", "East Hill Friends Church", 20, 70820);
INSERT INTO PARK_AND_RIDE Values ("Kent", "SE 248th St and 110th Ave SE", "Kent United Methodist Church", 23, 70820);
INSERT INTO PARK_AND_RIDE Values ("Kent", "26715 Military Rd S", "St. Columba's Episcopal Church", 15, 50703);
INSERT INTO PARK_AND_RIDE Values ("Kent", "12010 SE 240th St", "Kent Covenant Church", 20, 5419);
INSERT INTO PARK_AND_RIDE Values ("Kent", "N Lincoln Ave and W James St", "James St Park and Ride", 713, 3470);
INSERT INTO PARK_AND_RIDE Values ("Kent", "132nd Ave SE and SE 272nd St", "Lake Meridian Park and Ride", 172, 60453);
INSERT INTO PARK_AND_RIDE Values ("Kent", "I-5 and Kent Des Moines Rd", "Kent Des Moines Park and Ride", 370, 50480);
INSERT INTO PARK_AND_RIDE Values ("Kent", "I-5 and S 272nd St", "Star Lake Park and Ride", 540, 60453);
INSERT INTO PARK_AND_RIDE Values ("Kent", "301 Railroad Ave N", "Kent Garage at Kent Station", 877, 57453);
INSERT INTO PARK_AND_RIDE Values ("Kent", "301 Railroad Ave N", "Kent Surface Lot at Kent Station", 119, 57453);
INSERT INTO PARK_AND_RIDE Values ("Kirkland", "14220 Juanita-Woodinville Way NE", "Korean Covenant Church of Kirkland", 30, 84031);
INSERT INTO PARK_AND_RIDE Values ("Kirkland", "Kirkland Way and NE 85th St", "Kirkland Way Park and Ride", 20, 35530);
INSERT INTO PARK_AND_RIDE Values ("Kirkland", "I-405 and NE 132nd St", "Kingsgate Park and Ride", 502, 71341);
INSERT INTO PARK_AND_RIDE Values ("Kirkland", "I-405 and NE 70th Pl", "Houghton Park and Ride", 470, 5419);
INSERT INTO PARK_AND_RIDE Values ("Kirkland", "NE 124th St and 100th Ave NE", "Holy Spirit Lutheran Church", 40, 74232);
INSERT INTO PARK_AND_RIDE Values ("Kirkland", "NE 38th PL and NE 37th Circle", "South Kirkland Park and Ride", 833, 74450);
INSERT INTO PARK_AND_RIDE Values ("Maple Valley", "SE 231st St and Renton-Maple Valley Rd (SR 169)", "Maple Valley Park and Ride", 122, 64413);
INSERT INTO PARK_AND_RIDE Values ("Maple Valley", "26520 Maple Valley Highway", "Maple Valley Town Square", 97, 99330);
INSERT INTO PARK_AND_RIDE Values ("Medina", "SR 520 and 76th Ave NE", "Evergreen Point Bridge", 48, 10030);
INSERT INTO PARK_AND_RIDE Values ("Mercer Island", "80th Ave SE and N Mercer Way", "Mercer Island Park and Ride", 447, 375);
INSERT INTO PARK_AND_RIDE Values ("Mercer Island", "86th Ave SE and Island Crest Way", "Congregational Church of Mercer Island", 28, 67015);
INSERT INTO PARK_AND_RIDE Values ("Mercer Island", "84th Ave SE and SE 36th St", "Mercer Island Presbyterian Church", 14, 66880);
INSERT INTO PARK_AND_RIDE Values ("Mercer Island", "SE 24th St and 70th Ave SE", "Mercer Island United Methodist Church", 18, 85842);
INSERT INTO PARK_AND_RIDE Values ("Mercer Island", "SE 68th St and 84th Ave SE", "Mercer Island QFC Village", 21, 70820);
INSERT INTO PARK_AND_RIDE Values ("Normandy Park", "North side of First Ave S, near 192nd Ave", "Normandy Park Congregational Church", 10, 75730);
INSERT INTO PARK_AND_RIDE Values ("North Bend", "W North Bend Way and Sydney Ave", "North Bend Park and Ride", 80, 40068);
INSERT INTO PARK_AND_RIDE Values ("Preston", "I-90 and SE 82nd St, east of interstate", "Preston Park and Ride", 53, 47973);
INSERT INTO PARK_AND_RIDE Values ("Redmond", "17371 NE 24th St", "Holy Trinity Church", 17, 5419);
INSERT INTO PARK_AND_RIDE Values ("Redmond", "NE Cedar Park Crescent and Redmond Ridge Dr NE", "Redmond Ridge", 52, 72521);
INSERT INTO PARK_AND_RIDE Values ("Redmond", "161st Ave NE and NE 83rd St", "Redmond Park and Ride", 377, 73227);
INSERT INTO PARK_AND_RIDE Values ("Redmond", "178th PL NE and NE Union Hill Rd", "Bear Creek Park and Ride", 283, 81755);
INSERT INTO PARK_AND_RIDE Values ("Redmond", "152nd Ave NE and NE 24th St", "Overlake Park and Ride", 203, 68390);
INSERT INTO PARK_AND_RIDE Values ("Renton", "131st Ave SE and SE 192nd St", "NW Life Church", 25, 60453);
INSERT INTO PARK_AND_RIDE Values ("Renton", "S 2nd and Burnett Ave", "Renton Park and Ride", 150, 46479);
INSERT INTO PARK_AND_RIDE Values ("Renton", "655 S 2nd St (garage floors 4-7)", "Renton City Municipal Garage", 150, 46479);
INSERT INTO PARK_AND_RIDE Values ("Renton", "Park Ave N and N 30th St", "Kennydale United Methodist Church", 50, 45219);
INSERT INTO PARK_AND_RIDE Values ("Renton", "NE 16th St and Edmonds Ave NE", "St. Matthew Lutheran Church", 128, 56570);
INSERT INTO PARK_AND_RIDE Values ("Renton", "365 Renton Center Way SW", "Fred Meyer", 21, 64413);
INSERT INTO PARK_AND_RIDE Values ("Renton", "Hardie Ave SW and SW Langston Rd", "City View Church", 96, 11910);
INSERT INTO PARK_AND_RIDE Values ("Renton", "140th Ave SE and SE 177th St", "Nativity Lutheran Church", 49, 75995);
INSERT INTO PARK_AND_RIDE Values ("Renton", "152nd and Renton-Maple Valley Hwy", "New Life Church", 25, 99390);
INSERT INTO PARK_AND_RIDE Values ("Renton", "S Grady Way and Shattuck Ave S", "South Renton Park and Ride", 373, 59904);
INSERT INTO PARK_AND_RIDE Values ("Renton", "Union Ave NE and NE 10th St", "Renton Bible Church", 50, 81294);
INSERT INTO PARK_AND_RIDE Values ("Sammamish", "228th Ave SE and Issaquah-Pine Lake Rd", "South Sammamish Park and Ride", 265, 20700);
INSERT INTO PARK_AND_RIDE Values ("Sammamish", "SE 8th S and 228th Ave SE", "Sammamish Hills Lutheran Church", 54, 70820);
INSERT INTO PARK_AND_RIDE Values ("SeaTac", "15247 International Blvd", "SeaTac Center Garage", 62, 31610);
INSERT INTO PARK_AND_RIDE Values ("SeaTac", "19955 28th Ave S", "Angle Lake", 1160, 80710);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "11659 1st Ave S", "Beverly Park First Baptist Church", 12, 14960);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "11227 Renton Ave S", "Community Bible Fellowship", 29, 46463);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "610 SW Roxbury", "Sonrise Evangelical Free Church", 10, 21080);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "26th Ave SW and SW Spokane St", "Southwest Spokane St. Park and Ride", 55, 15140);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "Olson Pl SW and Myers Way S", "Olson Place and Myers Way Park and Ride", 100, 58467);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "I-5 and NE 65th St", "Green Lake Park and Ride", 411, 5419);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "SW Roxbury St and 20th Ave SW", "Holy Family Church", 23, 22557);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "3rd Ave NE and NE 100th St", "Thornton Place Garage", 350, 81294);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "5th Ave NE and NE 133rd St", "5th Ave NE/NE 133rd St", 46, 23170);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "1st Ave NE and NE 103rd St", "Northgate Transit Center", 75, 73227);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "3rd Ave NE and NE 103rd St (just east of Northgate Transit Center)", "Northgate Transit Center Extension", 448, 35295);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "401 NE Northgate Way (garage 1st and 2nd floors)", "Northgate Mall Garage", 280, 40068);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "NW corner of NE 103rd and 5th Ave NE", "North Seattle Interim (Lot A)", 155, 74450);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "9580 1st Ave NE", "North Transit Center Interim (Lot B)", 99, 74450);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "10001 1st Ave NE", "North Seattle", 102, 71960);
INSERT INTO PARK_AND_RIDE Values ("Seattle", "Airport Way S and S Spokane St", "Airport &amp; Spokane", 25, 15190);
INSERT INTO PARK_AND_RIDE Values ("Shoreline", "17920 Meridian Ave N", "Korean Zion Presbyterian Church", 25, 75756);
INSERT INTO PARK_AND_RIDE Values ("Shoreline", "14514 20th Ave NE", "Prince of Peace Lutheran Church", 20, 81456);
INSERT INTO PARK_AND_RIDE Values ("Shoreline", "175th St and Meridian Ave N", "Aurora Church of the Nazarene", 116, 75756);
INSERT INTO PARK_AND_RIDE Values ("Shoreline", "NE 175th and 10th Ave NE", "Buddha Jewel Monastery", 40, 82230);
INSERT INTO PARK_AND_RIDE Values ("Shoreline", "Aurora Ave N and N 192nd St", "Shoreline Park and Ride", 393, 75730);
INSERT INTO PARK_AND_RIDE Values ("Shoreline", "NE 145th St and 25th Ave NE", "Shoreline United Methodist Church", 20, 82230);
INSERT INTO PARK_AND_RIDE Values ("Shoreline", "N 200th S and Meridian Ave N", "Aurora Village Transit Center", 202, 75756);
INSERT INTO PARK_AND_RIDE Values ("Shoreline", "5th Ave NE near I-5 and NE 145th St", "North Jackson Park and Ride", 68, 23170);
INSERT INTO PARK_AND_RIDE Values ("Snoqualmie", "35016 SE Ridge St", "Snoqualmie Community Park", 20, 71341);
INSERT INTO PARK_AND_RIDE Values ("Tukwila", "7301 Longacres Way", "Tukwila Sounder Station", 390, 67015);
INSERT INTO PARK_AND_RIDE Values ("Tukwila", "13445 Interurban Ave S", "Tukwila Park and Ride", 267, 80710);
INSERT INTO PARK_AND_RIDE Values ("Tukwila", "International Blvd and Southcenter Blvd", "Tukwila International Blvd Station", 600, 31610);
INSERT INTO PARK_AND_RIDE Values ("Tukwila", "S 148th St and Pacific Hwy S", "Church by the Side of the Road", 28, 52302);
INSERT INTO PARK_AND_RIDE Values ("Vashon Island", "Vashon Hwy SW and SW 171st St", "Ober Park Park and Ride", 48, 85170);
INSERT INTO PARK_AND_RIDE Values ("Vashon Island", "17130 Vashon Hwy SW", "Ober Park Annex", 9, 99330);
INSERT INTO PARK_AND_RIDE Values ("Vashon Island", "15420 Vashon Hwy SW", "Vashon Episcopal Church of the Holy Spirit", 23, 99330);
INSERT INTO PARK_AND_RIDE Values ("Vashon Island", "Vashon Hwy SW and SW 204th St", "Valley Center Park and Ride", 55, 60747);
INSERT INTO PARK_AND_RIDE Values ("Vashon Island", "13223 SW Tahlequah Rd", "Tahlequah Park and Ride", 36, 99294);
INSERT INTO PARK_AND_RIDE Values ("Woodinville", "15737 Avondale Rd", "Cottage Lake Assembly of God", 20, 11012);
INSERT INTO PARK_AND_RIDE Values ("Woodinville", "19020 NE Woodinville-Duvall Rd", "Woodinville Unitarian Universalist Church", 30, 84031);
INSERT INTO PARK_AND_RIDE Values ("Woodinville", "140th Ave NE and NE 179th St", "Woodinville Park and Ride", 438, 75995);
