CREATE TABLE EMPLOYEE(
    ID INT UNIQUE,
    Ssn CHAR(11) UNIQUE NOT NULL,
    E_Name VARCHAR(30) NOT NULL,

    PRIMARY KEY(ID),
    CONSTRAINT ID_range CHECK(ID >= 0),
    CONSTRAINT Name_range CHECK(LEN(E_Name) <= 3 AND LEN(E_Name) <= 30)
);